name: h1dr8
favicon: null
layout_spectrum: 0.15862
typography_spectrum: 0.5470963746774942
title: h1dr8 - feel great
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d3091'
    - '#eb008a'
    - '#8a188d'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.5
  lightness: 0.6870231099892408
  saturation: 0.8370931015815586
  rhythmicContrast: 0.7758236185181886
purpose: []
